### ISSUE TITLE
Colab notebook ImportError:  cannot import name 'download_and_convert_to_mp3' from 'whisperplus'

### ISSUE THREAD

**Issue by stevevaius2015** [kadirnar/whisper-plus#110]
I can not run Colab notebook to test it. I received following error on `from whisperplus import SpeechToTextPipeline, download_and_convert_to_mp3` section

`ImportError: cannot import name 'download_and_convert_to_mp3' from 'whisperplus' (/usr/local/lib/python3.10/dist-packages/whisperplus/__init__.py)`

**Comment by kadirnar** [comment]
I updated the functions. You can look at the readme file.
```python
from whisperplus import SpeechToTextPipeline, download_youtube_to_mp3

url = "https://www.youtube.com/watch?v=di3rHkEZuUw"
audio_path = download_youtube_to_mp3(url, output_dir="downloads", filename="test")
```
