### ISSUE TITLE
Does diarization support other languages?

### ISSUE THREAD

**Issue by behroozazarkhalili** [kadirnar/whisper-plus#114]
Hi @kadirnar,
Thank you for this great package.

My question is if it supports another language in the diarization pipeline. If so, could you please provide a simple example?

**Comment by kadirnar** [comment]
I don't know which languages it supports. But it supports multiple languages. I tested it for Turkish and English. But the accuracy rate may be low.

**Comment by behroozazarkhalili** [comment]
Could you please provide an example of how we can add the language variable to the model?

**Comment by kadirnar** [comment]
<img width="684" alt="image" src="https://github.com/kadirnar/whisper-plus/assets/36204372/43f7ce95-5f2c-4995-8854-050d6e5a2c16">
