### ISSUE TITLE
Which whisper implementation you used?

### ISSUE THREAD

**Issue by behroozazarkhalili** [kadirnar/whisper-plus#115]
Hi @kadirnar,
Have you used insanely-faster-whisper in your projects? It seems the fastest whisper implementation and it would be great if we could have it. 

Best,
Behrooz

**Comment by kadirnar** [comment]
WhisperPlus library is faster than insanely-faster-whisper library. You should use hqq optimization.

**Comment by behroozazarkhalili** [comment]
Thank you. Can you provide me with any concrete example of using hqq optimization?

**Comment by kadirnar** [comment]
<img width="682" alt="image" src="https://github.com/kadirnar/whisper-plus/assets/36204372/278d2a5b-febc-48d8-afca-87085d4e10fd">
