### ISSUE TITLE
[Feature Request] Text-to-Speech with Bark Model 🔊

### ISSUE THREAD

**Issue by kadirnar** [kadirnar/whisper-plus#12]
Implement code for text-to-speech using the Bark model. Enable the generation of high-quality audio from input text, leveraging the capabilities of the Bark model for a natural and expressive voice. 🌲🔊

🌐 Example Demo: [Colab bark text2speech](https://colab.research.google.com/drive/1eJfA2XUa-mXwdMy7DoYKVYHI1iTd9Vkt?usp=sharing)
📚 Example Doc: [text-to-speech-bark](https://github.com/suno-ai/bark)

**Comment by GuldenizBektas** [comment]
Working on it! :) Fingers crossed
