### ISSUE TITLE
Does the speaker diarization totally using pyannote or are there some embedding sharing?

### ISSUE THREAD

**Issue by lucasjinreal** [kadirnar/whisper-plus#20]
Does the speaker diarization totally using pyannote or are there some embedding sharing?

pyannoate diarizaiton on other language are not very accurate.

**Comment by kadirnar** [comment]
I used the pyannoate library.

Code: https://github.com/kadirnar/whisper-plus/blob/main/whisperplus/pipelines/whisper_diarize.py
