### ISSUE TITLE
is there any way to form srt file for subtitle?

### ISSUE THREAD

**Issue by bk111** [kadirnar/whisper-plus#37]
is there any way to form srt file for subtitle?

**Comment by kadirnar** [comment]
You can save it in .txt format. It may be necessary to write extra code for .srt.

**Comment by akashAD98** [comment]
i will add support for this in sometime

**Comment by kadirnar** [comment]
> i will add support for this in sometime

Is there an update?

**Comment by kadirnar** [comment]
> [@kadirnar](https://github.com/kadirnar) Found it, must be WhisperAutoCaptionPipeline

Yes, I added it. It's not perfect, but it works well.
