### ISSUE TITLE
[Feature Request] Add Text Summarization with Open Source LLM Models 📚

### ISSUE THREAD

**Issue by kadirnar** [kadirnar/whisper-plus#4]
Description:

Implement code to perform text summarization using open source language models after enabling text generation from audio data 📚

**Comment by kadirnar** [comment]
> Hi @kadirnar Can I work on this issue? or any other issue you need help with.

Hi, Text Summarization feature has been added to [this pull request](https://github.com/kadirnar/whisper-plus/pull/10). Do you want to add other features? Or you can add different features.

**Comment by StatKumar** [comment]
Sure I would love to add other features. Do you have any ideas?
