### ISSUE TITLE
404 error - Huggingface Link

### ISSUE THREAD

**Issue by trivikramak** [kadirnar/whisper-plus#45]
https://huggingface.co/spaces/ArtGAN/WhisperPlus - This link isn't working.

**Comment by kadirnar** [comment]
I will update it over the weekend.

**Comment by kadirnar** [comment]
Can you check? @trivikramak

**Comment by trivikramak** [comment]
Still getting a 404 .. am I missing something?

**Comment by kadirnar** [comment]
New Link: https://huggingface.co/spaces/ArtGAN/Audio-WebUI
