### ISSUE TITLE
huggingface token required

### ISSUE THREAD

**Issue by jhmejia** [kadirnar/whisper-plus#60]
When running the [sample diarization pipeline](https://github.com/kadirnar/whisper-plus?tab=readme-ov-file#-speaker-diarization), I get: 

```
Could not download 'pyannote/speaker-diarization' pipeline.

It might be because the pipeline is private or gated so make
sure to authenticate. Visit https://hf.co/settings/tokens to
create your access token and retry with:

   >>> Pipeline.from_pretrained('pyannote/speaker-diarization',
   ...                          use_auth_token=YOUR_AUTH_TOKEN)
```

Where would I include the auth token in the function call? 

Or would I have to include it in the env? etc.

**Comment by kadirnar** [comment]
You need to confirm this on the HuggingFace site.

<img width="502" alt="image" src="https://github.com/kadirnar/whisper-plus/assets/36204372/81ff7266-5ad8-4fa0-ad78-239d11e7fcb2">

**Comment by jhmejia** [comment]
I did, but am not sure how to connect my hugging face account to the code I'm running via an auth token. Where would I put one in?

**Comment by kadirnar** [comment]
You don't need to write code. You must allow it. Does it say this on the model sheet?

![image](https://github.com/kadirnar/whisper-plus/assets/36204372/123ed92c-807b-4636-993b-57f8b6052147)

**Comment by jhmejia** [comment]
It does, see image!

![image](https://github.com/kadirnar/whisper-plus/assets/29128358/4cf44248-9de9-47c2-b612-c951433a2af3)

However I am not sure how to connect my account to the repo: this is just python 3.10 that is not connected to huggingface in any way: 
![image](https://github.com/kadirnar/whisper-plus/assets/29128358/54184e76-3444-4096-ba05-198dfcf13bcd)

**Comment by jhmejia** [comment]
Bug SOLVED: 
1. You must both agree to the [speaker diarization pipeline](https://huggingface.co/pyannote/speaker-diarization) AND the [segmentation pipeline](https://huggingface.co/pyannote/segmentation)
2.  You must include [your access token](https://huggingface.co/settings/tokens) as follows:

```py
pipeline = ASRDiarizationPipeline.from_pretrained(
    asr_model="openai/whisper-large-v3",
    diarizer_model="pyannote/speaker-diarization",
    use_auth_token="[INSERT YOUR TOKEN HERE]",
    chunk_length_s=30,
    device=device,
)
```

Alternatively, you can leave it `False` as the example says,  and then include your huggingface config token in your home directory:

In ~/.huggingface/config.json:
```json
{
   "hf_token": "[insert token]"
}```
