### ISSUE TITLE
discussion: how to clear the gpu memory usage done

### ISSUE THREAD

**Issue by nawed2611** [kadirnar/whisper-plus#68]
In this snippet where we initialise a `whisperplus` pipeline, how to clear out this memory usage once its used. 

```
pipeline = ASRDiarizationPipeline.from_pretrained(
        asr_model="openai/whisper-large-v3",
        diarizer_model="pyannote/speaker-diarization",
        chunk_length_s=30,
        device=DEVICE,
        use_auth_token=<auth_token>
    )
```

Would appreciate some help on this. I tried `del pipeline` but it doesn't seem to work

**Comment by kadirnar** [comment]
> In this snippet where we initialise a `whisperplus` pipeline, how to clear out this memory usage once its used.
> 
> ```
> pipeline = ASRDiarizationPipeline.from_pretrained(
>         asr_model="openai/whisper-large-v3",
>         diarizer_model="pyannote/speaker-diarization",
>         chunk_length_s=30,
>         device=DEVICE,
>         use_auth_token=<auth_token>
>     )
> ```
> 
> Would appreciate some help on this. I tried `del pipeline` but it doesn't seem to work

Can you try this code?

  def release_resources(self):
      """
      Releases resources and clears GPU memory cache. This method should be called after processing is complete,
      especially when processing multiple files in a loop, to ensure that GPU memory is freed.
      """
      if self.device == "cuda":
          torch.cuda.empty_cache()
      self.asr_pipeline = None
      self.diarization_pipeline = None

**Comment by nawed2611** [comment]
Thanks for this!
