### ISSUE TITLE
new Installation - many errors in Conda Python 3.8, 3.10 and 3.12

### ISSUE THREAD

**Issue by PiotrEsse** [kadirnar/whisper-plus#82]
Hi, 
I am trying to install WhisperPlud but face many issues. 

```
Traceback (most recent call last):
  File "/home/piotr/WhisperPlus/Tutorial/caption.py", line 1, in <module>
    from whisperplus import WhisperAutoCaptionPipeline
ImportError: cannot import name 'WhisperAutoCaptionPipeline' from 'whisperplus' (/home/piotr/anaconda3/envs/WhisperPlus310/lib/python3.10/site-packages/whisperplus/__init__.py)

```

OR

```
Traceback (most recent call last):
  File "/home/piotr/WhisperPlus/Tutorial/youtubetoaudio.py", line 20, in <module>
    bnb_4bit_compute_dtype=torch.bfloat16,
NameError: name 'torch' is not defined
```

I have new Installation - many errors in Conda Python 3.8, 3.10 and 3.12
Ive created new conda and follow instalation procedure: 

```
pip install whisperplus git+https://github.com/huggingface/transformers

pip install flash-attn --no-build-isolation

```

Nvidia Cuda toolkit 12.4, nevest drivers.

**Comment by kadirnar** [comment]
I will fix this bug in the new version.

```python
from whisperplus.pipelines.whisper_autocaption import WhisperAutoCaptionPipeline

caption = WhisperAutoCaptionPipeline(model_id="openai/whisper-large-v3")
caption(video_path="test.mp4", output_path="output.mp4", language="turkish")
```

**Comment by kadirnar** [comment]
I released a new version. You can use this.

```bash
pip install whisperplus==0.3.1
```

**Comment by PiotrEsse** [comment]
Thank You, there are new error message: 

```
  File "/home/piotr/WhisperPlus/Tutorial/Diarization.py", line 1, in <module>
    from whisperplus import (
  File "/home/piotr/anaconda3/envs/WhisperPlus310/lib/python3.10/site-packages/whisperplus/__init__.py", line 1, in <module>
    from whisper.pipelines.whisper_autocaption import WhisperAutoCaptionPipeline
ModuleNotFoundError: No module named 'whisper'

```

**Comment by PiotrEsse** [comment]
Ive installed new Ubuntu24lts, install nvidia toolkit, driver, everything from the scratch, Python 3.8. The error persist: 

`
  File "/home/piotr/WhisperPlus/Tutorial/YoutubeToText.py", line 1, in <module>
    from whisperplus import SpeechToTextPipeline, download_and_convert_to_mp3
  File "/home/piotr/anaconda3/envs/WhisperPlus38/lib/python3.8/site-packages/whisperplus/__init__.py", line 1, in <module>
    from whisper.pipelines.whisper_autocaption import WhisperAutoCaptionPipeline
ModuleNotFoundError: No module named 'whisper'
`

**Comment by kadirnar** [comment]
https://github.com/kadirnar/whisper-plus/issues/86
